[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"
  NODE_ENV = "production"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_DATABASE_SETUP = "true"
  NEXT_DISABLE_SOURCEMAPS = "1"
  # Skip Next.js static generation to avoid Prisma issues
  NEXT_PRIVATE_SKIP_STATIC_GENERATION_DURING_BUILD = "1"
  NEXT_PRIVATE_PREBUNDLED_REACT = "next"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "/api"
