[build]
  command = "npm run netlify:build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"
  NODE_ENV = "production"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_DEPLOYMENT_ENV = "netlify"
  NEXT_DISABLE_SOURCEMAPS = "1"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_PRISMA_GENERATE = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**", "prisma/**"]

[context.production.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "/api"
