[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"
  NODE_ENV = "production"

# Next.js API routes will be converted to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle Next.js routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "/api"
