[build]
  command = "npm run prisma:generate && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"
  NODE_ENV = "production"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  # Skip Next.js static generation to avoid Prisma issues
  NEXT_PUBLIC_DEPLOYMENT_ENV = "netlify"
  NEXT_DISABLE_SOURCEMAPS = "1"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  # Increase the timeout for functions to accommodate longer operations
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**", "prisma/**"]

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "/api"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "/api"
